gateway:
  ignoredPatterns:
    - /api/*/service-api/**
    - /api/*//service-api/**
    - /api/*/integration-api/**
    - /api/*//integration-api/**
  csrf:
    enabled: true
    ignoredPaths:
      - /api/auth/login*/**
      - /api/auth/logout*/**

spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          default-filters:
            - ValidateRoutes
          routes:
            - id: product-service
              order: 0
              uri: lb://product-service
              predicates:
                - Path=/api/product/**
              filters:
                - RewritePath=/api/product/(?<remaining>.*), /${remaining}
                #- RewritePath=/api/product/(?<version>[^/]+)(?<remaining>/.*), /${version}${remaining}
                - name: CircuitBreaker
                  args:
                    name: productCircuitBreaker
                    fallbackUri: forward:/fallback/product
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter:
                      replenishRate: 10
                      burstCapacity: 20
                      requestedTokens: 1
                    key-resolver: "#{@ipKeyResolver}"

            - id: order-service
              order: 1
              uri: lb://order-service
              predicates:
                - Path=/api/order/**
              filters:
                - RewritePath=/api/order/(?<remaining>.*), /${remaining}
                #- RewritePath=/api/order/(?<version>[^/]+)(?<remaining>/.*), /${version}${remaining}
                - name: CircuitBreaker
                  args:
                    name: orderCircuitBreaker
                    fallbackUri: forward:/fallback/order
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter:
                      replenishRate: 10
                      burstCapacity: 20
                      requestedTokens: 1
                    key-resolver: "#{@ipKeyResolver}"

            - id: notification-service
              order: 2
              enabled: false
              uri: lb://notification-service
              predicates:
                - Path=/api/notification/**
              filters:
                - RewritePath=/api/notification/(?<remaining>.*), /${remaining}
                #- RewritePath=/api/notification/(?<version>[^/]+)(?<remaining>/.*), /${version}${remaining}
                - name: CircuitBreaker
                  args:
                    name: notificationCircuitBreaker
                    fallbackUri: forward:/fallback/notification
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter:
                      replenishRate: 10
                      burstCapacity: 20
                      requestedTokens: 1
                    key-resolver: "#{@ipKeyResolver}"
                - name: Retry
                  args:
                    retries: 3
                    methods: GET
                    statuses: BAD_GATEWAY,SERVICE_UNAVAILABLE,GATEWAY_TIMEOUT
                    backoff:
                      firstBackoff: 100ms
                      maxBackoff: 1s

            - id: dynamic-service-routing
              order: 3
              enabled: true
              #uri: "lb://#{servicePrefix}-service" # Dummy, replaced dynamically in DynamicRouting
              uri: lb://notification-service
              predicates:
                - Path=/api/{servicePrefix}/**
              filters:
                - DynamicRouting
                - name: RewritePath
                  args:
                    regexp: "/api/(?<servicePrefix>[^/]+)(?<remaining>/.*)"
                    replacement: "/${remaining}"
                - name: CircuitBreaker
                  args:
                    name: defaultCircuitBreaker
                    fallbackUri: forward:/fallback/default
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter:
                      replenishRate: 10
                      burstCapacity: 20
                      requestedTokens: 1
                    key-resolver: "#{@ipKeyResolver}"
                - name: Retry
                  args:
                    retries: 3
                    methods: GET
                    statuses: BAD_GATEWAY,SERVICE_UNAVAILABLE,GATEWAY_TIMEOUT
                    backoff:
                      firstBackoff: 100ms
                      maxBackoff: 1s

# Refer: io.github.resilience4j.common.circuitbreaker.configuration.CommonCircuitBreakerConfigurationProperties
resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 30
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        registerHealthIndicator: true
        permittedNumberOfCallsInHalfOpenState: 5
    instances:
      productCircuitBreaker:
        baseConfig: default
      orderCircuitBreaker:
        baseConfig: default
      notificationCircuitBreaker:
        baseConfig: default
      defaultCircuitBreaker:
        baseConfig: default
  timelimiter:
    configs:
      default:
        timeoutDuration: 3s
        cancelRunningFuture: true
    instances:
      productCircuitBreaker:
        baseConfig: default
      orderCircuitBreaker:
        baseConfig: default
      notificationCircuitBreaker:
        baseConfig: default
      defaultCircuitBreaker:
        baseConfig: default
