spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/products/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: productCircuitBreaker
                    fallbackUri: forward:/fallback/product
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter:
                      replenishRate: 10
                      burstCapacity: 20
                      requestedTokens: 1
                    key-resolver: "#{@ipKeyResolver}"

            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/orders/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: orderCircuitBreaker
                    fallbackUri: forward:/fallback/order
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter:
                      replenishRate: 10
                      burstCapacity: 20
                      requestedTokens: 1
                    key-resolver: "#{@ipKeyResolver}"

            - id: notification-service
              uri: lb://notification-service
              predicates:
                - Path=/notifications/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: notificationCircuitBreaker
                    fallbackUri: forward:/fallback/notification
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter:
                      replenishRate: 10
                      burstCapacity: 20
                      requestedTokens: 1
                    key-resolver: "#{@ipKeyResolver}"
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

# Refer: io.github.resilience4j.common.circuitbreaker.configuration.CommonCircuitBreakerConfigurationProperties
resilience4j:
  circuitbreaker:
    instances:
      productCircuitBreaker:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        registerHealthIndicator: true
  timelimiter:
    instances:
      productCircuitBreaker:
        timeoutDuration: 3s
