shedlock:
  defaultLockAtLeastFor: PT1S
  defaultLockAtMostFor: PT60M
spring:
  datasource:
    db-type: h2 # Allowed Value: [ h2, mysql, oracle, postgresql ]
    url: jdbc:h2:mem:identity
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/${spring.datasource.db-type}/master.yaml

app:
  info:
    name: ${spring.application.name}
  jobs:
    job-common:
      name: JOB_COMMON
      #cron: "*/10 * * * * *"
      cron: "-"
