shedlock:
  defaultLockAtLeastFor: PT1S
  defaultLockAtMostFor: PT60M

spring:
  datasource:
    db-type: h2 # Allowed Value: [ h2, mysql, oracle, postgresql ]
    #url: jdbc:h2:mem:identity
    url: jdbc:h2:file:./target/identity;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none # Allowed Value: [none,create,update,validate,drop,...]
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/${spring.datasource.db-type}/master.yaml
  security:
    ott:
      expiresIn: PT10M
    oauth2:
      authorizationserver:
        jwk:
          rotation:
            activeKeyId: rsa-2026-06
          keyStore:
            keyStore: classpath:keystore.p12
            keyStorePass: changeit
            keyStoreType: PKCS12

app:
  info:
    name: ${spring.application.name}
  scheduler:
    job-common:
      name: JOB_COMMON
      #cron: "*/10 * * * * *"
      cron: "-" # Disabled
