spring:
  datasource:
    url: jdbc:h2:mem:notificationdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    function:
      definition: notification
    stream:
      bindings:
        notification-in-0:
          destination: orders
          group: notification-group
          consumer:
            auto-startup: true

custom:
  message: "Welcome to the Notification Service!"
