spring:
  datasource:
    url: jdbc:h2:mem:orderdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
    stream:
      default-binder: rabbit
      bindings:
        order-out-0:
          destination: orders
          content-type: application/json
          producer:
            autoStartup: true

resilience4j:
  circuitbreaker:
    instances:
      product-service:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

custom:
  message: "Welcome to the Order Service!"
