spring:
  datasource:
    url: jdbc:h2:mem:orderdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
    stream:
      bindings:
        notificationOrderSupplier-out-0:
          destination: notification-order
          producer:
            autoStartup: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 30
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        registerHealthIndicator: true
        permittedNumberOfCallsInHalfOpenState: 5
    instances:
      product-service:
        baseConfig: default
  timelimiter:
    configs:
      default:
        timeoutDuration: 3s
        cancelRunningFuture: true
    instances:
      product-service:
        baseConfig: default

custom:
  message: "Welcome to the Order Service!"
