spring:
  datasource:
    url: jdbc:h2:mem:productdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

custom:
  message: "Welcome to the Product Service!"
