spring:
  datasource:
    url: jdbc:h2:mem:productdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

custom:
  message: "Welcome to the Product Service!"
